name: ä¸»åˆ†æ”¯æ¨é€ğŸ˜„
on:
  push:
    branches:
      - main
jobs:
  build-and-publsh:
    runs-on: ubuntu-20.04
    steps:
      - name: å¯åŠ¨ MySQL æœåŠ¡
        run: sudo systemctl start mysql.service

      - name: é…ç½®ç¯å¢ƒå˜é‡
        run: |
          echo "::set-env name=DB_HOST::localhost"
          echo "::set-env name=DB_PORT::3306"
          echo "::set-env name=DB_USER::root"
          echo "::set-env name=DB_PASSWORD::root"
          echo "::set-env name=DB_NAME::taills"

      - name: åˆ›å»ºæ•°æ®åº“
        run: |
          mysql -u${DB_USER} -p${DB_PASSWORD} -e "create database ${DB_NAME}"
          mysql -u${DB_USER} -p${DB_PASSWORD} -e "show databases"

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          server-id: ossrh
          server-username: NEXUS_USERNAME # env variable for username in deploy
          server-password: NEXUS_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Publish to Apache Maven Central
        run: mvn clean install deploy
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}